general {
    disable_loading_bar = true
    hide_cursor = true
}

background {
    color = rgba(0, 0, 0, 1.0)
}

label {
    text = cmd[update:1000] echo "$(date +'%H:%M:%S')"
    color = rgba(180, 180, 180, 1.0)
    font_size = 42
#    font_family = JetBrains Mono
    font_family = monospace
    position = 0, 80
    halign = center
    valign = center
}

input-field {
    size = 300, 50
    outline_thickness = 0
    dots_center = true
    dots_size = 0.25
    dots_spacing = 0.25

    font_color = rgba(255,255,255,1.0)
    inner_color = rgba(0,0,0,1.0)
    outer_color = rgba(0,0,0,0.0)

    fade_on_empty = false
   #placeholder_text = <span foreground="gray">Password</span>
    placeholder_text =

    position = 0, -40
    halign = center
    valign = center
}
